### ISSUE TITLE
Move dropdown menu for memory display type

### ISSUE THREAD

**Issue by mitchellrobert** [Guillaume-Savaton-ESEO/emulsiV#10]
I have found that the dropdown menu for choosing the way the memory is displayed to be quite useful for quickly converting between instructions, unsigned decimals, etc. However, it ideally would be placed outside of the scrolling box so that the user does not need to scroll all the way to the lowest memory address to toggle between modes, and then scroll all they way back to where they previously were in the memory list.

**Comment by Guillaume-Savaton-ESEO** [comment]
I agree.

It is a common problem in web applications to have a "sticky" row or column in a table.
Last time I checked, it was not supported natively, but there were workarounds.

**Comment by Guillaume-Savaton-ESEO** [comment]
It was surprisingly easy. You can try it now at https://guillaume-savaton-eseo.github.io/emulsiV/ and tell me whether it works for you.
This feature is probably not compatible with old web browsers.

**Comment by mitchellrobert** [comment]
I am sorry for the late reply! The sticky dropdown menu works beautifully.
Thanks alot!
