### ISSUE TITLE
Are there any bugs in the lui instruction?

### ISSUE THREAD

**Issue by qq516333132** [Guillaume-Savaton-ESEO/emulsiV#21]
"lui x1, 0xA" Unacceptable?
"lui x1, 0x1000" run result 0x1000000, but not 0x1000

用汇编学习risc-v指令集，并在线仿真，点亮led
https://whycan.com/t_6593.html#p64755

**Comment by Guillaume-Savaton-ESEO** [comment]
According to the RISC-V specification, LUI is a U-type instruction where the immediate field contains 20 bits identified as `imm[31:12]`.

If we take the instruction `lui x1, 0x1000`, I think there are two possible interpretations:
1. `imm` is `0x1000` (and so `imm[31:12]` is `0x1`)
2. `imm[31:12]` is `0x1000` (`imm` is `0x1000000`)

I honestly don't know which interpretation is right. As far as I remember, this is not explicitly defined in the RISC-V spec.
emulsiV follows the first, and I personally find it easier to understand for beginners. But I know that the GNU toolchain uses the second.

**Comment by pcotret** [comment]
So, I assume we should have the same behavior with other U-type instructions ? (thinking about `auipc`)
